<?php

/**
 * @file
 * Contains usdoj_most_wanted.module.
 */

use Drupal\node\Entity\Node;
use Drupal\taxonomy\Entity\Term;

/**
 * Runs most wanted feeds on cron.
 */
function usdoj_most_wanted_cron() {

  if (date('G') == 2) {
    $i = 1;
    // Determine total number of items and pages in Most Wanted JSON.
    $response = \Drupal::httpClient()->get('https://api.fbi.gov/@wanted?pageSize=50&page=1');
    $response_body = $response->getBody();
    $items = json_decode($response_body->getContents());
    $total_items = ceil($items->total / 100) * 100;
    $pages = $total_items / 50;

    do {
      // Programmatically create a feed to import items.
      $feed = \Drupal::entityTypeManager()->getStorage('feeds_feed')->create([
        'type' => 'most_wanted',
        'uuid' => \Drupal::service('uuid')->generate(),
        'title' => 'Most wanted feed',
        'uid' => 1,
        'status' => 1,
        'created' => time(),
        'source' => "https://api.fbi.gov/@wanted?pageSize=50&page=" . $i,
      ]);
      $feed->save();
      $feed->import();
      $feed->delete();

      // Keep only results that are tagged as top ten most wanted.
      // Not the most ideal solution to retain only the top ten most
      // wanted results but the endpoint doesnt accept
      // 'subjects' as a parameter for some reason.
      $nids = \Drupal::entityQuery('node')->condition('type', 'most_wanted')->execute();
      $nodes = Node::loadMultiple($nids);
      foreach ($nodes as $node) {
        if (($node->get('field_most_wanted_category')->isEmpty())) {
          $node->delete();
        }
        else {
          $tid = $node->get('field_most_wanted_category')->getValue();
          $name = Term::load($tid[0]['target_id'])->get('name')->value;
          if ($name !== 'Ten Most Wanted Fugitives') {
            $node->delete();
          }
        }
      }

      $i++;
    } while ($i <= $pages);
  }
}
